version: '3.7'
services:
  web:
    build: ./app
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    # network_mode: "host"
  


