# Generated by Django 3.2.4 on 2021-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default=None, max_length=100)),
                ('ipaddress', models.CharField(default=None, max_length=100)),
                ('macaddress', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
