# Generated by Django 3.2.4 on 2021-06-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='vulners',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
